# Aastha Basu 2022UG000022

# 1. Text Preprocessing with Pandas

In [1]:
import pandas as pd

pd.set_option('display.max_colwidth', None)

df = pd.read_csv('childrens_books.csv')
df.head()

,Ranking,Title,Author,Year,Rating,Description
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story."
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education."
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice."
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers."
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading."

- text preprocessing in pandas
- text preprocessing in spacy
- CountVectorizer (with barh)
- TF-IDF Vectorizer (with EDA)

In [2]:
df['cleaned_desc'] = df['Description'].str.lower()
df.head()

,Ranking,Title,Author,Year,Rating,Description,cleaned_desc
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.","where the wild things are follows max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. as their king, max tames the beasts and eventually returns home to find his supper waiting for him. this iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through sendak's whimsical illustrations and story."
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education.","the very hungry caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. eric carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. the simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. it’s a staple in early childhood education."
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice.","the giving tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. as the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. it has sparked much discussion about relationships and sacrifice."
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers.","in green eggs and ham, sam-i-am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. through repetition and rhyme, dr. seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. the playful illustrations and humorous dialogue make it a fun and educational read for young readers."
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading.","goodnight moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" its repetitive structure and comforting tone make it ideal for young children. the simple illustrations by clement hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading."

In [3]:
df['cleaned_desc'] = df['Description'].str.replace(r'\[.*?\]', '', regex=True)
df.head()

,Ranking,Title,Author,Year,Rating,Description,cleaned_desc
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.","Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story."
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education.","The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education."
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice.","The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice."
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers.","In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers."
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading.","Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading."

In [4]:
df['cleaned_desc'] = df['cleaned_desc'].str.replace(r'[^\w\s]', '', regex=True)
df.head()

,Ranking,Title,Author,Year,Rating,Description,cleaned_desc
0,1,Where the Wild Things Are,Maurice Sendak,1963,4.25,"Where the Wild Things Are follows Max, a young boy who, after being sent to his room for misbehaving, imagines sailing to an island filled with wild creatures. As their king, Max tames the beasts and eventually returns home to find his supper waiting for him. This iconic book explores themes of imagination, adventure, and the complex emotions of childhood, all captured through Sendak's whimsical illustrations and story.",Where the Wild Things Are follows Max a young boy who after being sent to his room for misbehaving imagines sailing to an island filled with wild creatures As their king Max tames the beasts and eventually returns home to find his supper waiting for him This iconic book explores themes of imagination adventure and the complex emotions of childhood all captured through Sendaks whimsical illustrations and story
1,2,The Very Hungry Caterpillar,Eric Carle,1969,4.34,"The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly. Eric Carle’s use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers. The simple, engaging story introduces children to days of the week, counting, and the concept of metamorphosis. It’s a staple in early childhood education.",The Very Hungry Caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly Eric Carles use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers The simple engaging story introduces children to days of the week counting and the concept of metamorphosis Its a staple in early childhood education
2,3,The Giving Tree,Shel Silverstein,1964,4.38,"The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life. As the boy grows up, he takes more from the tree, and the tree continues to give, even when it has little left. Silverstein’s minimalist text and illustrations convey deep themes of unconditional love, selflessness, and the passage of time. It has sparked much discussion about relationships and sacrifice.",The Giving Tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life As the boy grows up he takes more from the tree and the tree continues to give even when it has little left Silversteins minimalist text and illustrations convey deep themes of unconditional love selflessness and the passage of time It has sparked much discussion about relationships and sacrifice
3,4,Green Eggs and Ham,Dr. Seuss,1960,4.31,"In Green Eggs and Ham, Sam-I-Am tries to convince a reluctant character to try a dish of green eggs and ham, despite his resistance. Through repetition and rhyme, Dr. Seuss’s classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone. The playful illustrations and humorous dialogue make it a fun and educational read for young readers.",In Green Eggs and Ham SamIAm tries to convince a reluctant character to try a dish of green eggs and ham despite his resistance Through repetition and rhyme Dr Seusss classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone The playful illustrations and humorous dialogue make it a fun and educational read for young readers
4,5,Goodnight Moon,Margaret Wise Brown,1947,4.31,"Goodnight Moon is a gentle, rhythmic bedtime story where a little bunny says goodnight to everything in his room, from the moon to the ""quiet old lady whispering hush."" Its repetitive structure and comforting tone make it ideal for young children. The simple illustrations by Clement Hurd complement the soothing nature of the story, making it a beloved classic for sleep-time reading.",Goodnight Moon is a gentle rhythmic bedtime story where a little bunny says goodnight to everything in his room from the moon to the quiet old lady whispering hush Its repetitive structure and comforting tone make it ideal for young children The simple illustrations by Clement Hurd complement the soothing nature of the story making it a beloved classic for sleeptime reading

## lower_replace()

In [5]:
def lower_replace (series):
    output = series.str.lower()
    output = output.str.replace(r'\[.*?\]', '', regex=True)
    output = output.str.replace(r'[^\w\s]', '', regex=True)
    return output

lower_replace(df.Description)

0                            where the wild things are follows max a young boy who after being sent to his room for misbehaving imagines sailing to an island filled with wild creatures as their king max tames the beasts and eventually returns home to find his supper waiting for him this iconic book explores themes of imagination adventure and the complex emotions of childhood all captured through sendaks whimsical illustrations and story
1                                the very hungry caterpillar tells the story of a caterpillar who eats through a variety of foods before eventually becoming a butterfly eric carles use of colorful collage illustrations and rhythmic text has made this book a beloved classic for young readers the simple engaging story introduces children to days of the week counting and the concept of metamorphosis its a staple in early childhood education
2            the giving tree is a touching and bittersweet story about a tree that gives everything it has to a boy over the course of his life as the boy grows up he takes more from the tree and the tree continues to give even when it has little left silversteins minimalist text and illustrations convey deep themes of unconditional love selflessness and the passage of time it has sparked much discussion about relationships and sacrifice
3                                           in green eggs and ham samiam tries to convince a reluctant character to try a dish of green eggs and ham despite his resistance through repetition and rhyme dr seusss classic story about being open to new experiences encourages children to be adventurous and try things outside their comfort zone the playful illustrations and humorous dialogue make it a fun and educational read for young readers
4                                                                goodnight moon is a gentle rhythmic bedtime story where a little bunny says goodnight to everything in his room from the moon to the quiet old lady whispering hush its repetitive structure and comforting tone make it ideal for young children the simple illustrations by clement hurd complement the soothing nature of the story making it a beloved classic for sleeptime reading
                                                                                                                                                                                                                             ...
95                                                     stone soup is a classic folktale retold by jon j muth in which three soldiers arrive in a village claiming they can make soup from stones the villagers initially hesitant eventually contribute ingredients to the pot and together they create a delicious meal this story is a heartwarming lesson about sharing community and cooperation enhanced by muths beautiful watercolor illustrations
96                               a light in the attic is a collection of quirky poems and illustrations by shel silverstein exploring a wide range of topics with wit humor and imagination the poems are funny thoughtful and sometimes absurd but they all carry a sense of wonder and creativity silversteins distinctive voice and whimsical illustrations make this book a timeless collection that continues to entertain children and adults alike
97                             harry potter and the prisoner of azkaban is the third book in the harry potter series where harry returns to hogwarts for his third year and uncovers secrets about his past with the arrival of the mysterious sirius black harry must navigate dark truths and face his fears this thrilling installment explores themes of loyalty friendship and identity marking a turning point in the magical world of harry potter
98                                  harry potter and the chamber of secrets is the second book in the harry potter series where harry returns to hogwarts for his second year and uncovers a hidden chamber within the school as mysterious events unfold harry and his friends ron and hermione uncover dark secrets about the schools past themes of courage friendship and standing up for whats right are explored in this gripping magical adventure
99    the three billy goats gruff is a retelling of the classic norwegian fairy tale about three goats who must outwit a greedy troll to cross a bridge and reach greener pastures the goats each come up with a clever strategy to trick the troll teaching children lessons about teamwork bravery and cleverness galdones illustrations and simple rhythmic text bring the tale to life in a way that is accessible and entertaining for young readers
Name: Description, Length: 100, dtype: object

In [6]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [7]:
phrase = df.cleaned_desc[0]
phrase

'Where the Wild Things Are\xa0follows Max a young boy who after being sent to his room for misbehaving imagines sailing to an island filled with wild creatures As their king Max tames the beasts and eventually returns home to find his supper waiting for him This iconic book explores themes of imagination adventure and the complex emotions of childhood all captured through Sendaks whimsical illustrations and story'

In [8]:
doc = nlp(phrase)
doc

Where the Wild Things Are follows Max a young boy who after being sent to his room for misbehaving imagines sailing to an island filled with wild creatures As their king Max tames the beasts and eventually returns home to find his supper waiting for him This iconic book explores themes of imagination adventure and the complex emotions of childhood all captured through Sendaks whimsical illustrations and story

In [9]:
[token.lemma_ for token in doc]

['where',
 'the',
 'Wild',
 'Things',
 'be',
 '\xa0',
 'follow',
 'Max',
 'a',
 'young',
 'boy',
 'who',
 'after',
 'be',
 'send',
 'to',
 'his',
 'room',
 'for',
 'misbehave',
 'imago',
 'sail',
 'to',
 'an',
 'island',
 'fill',
 'with',
 'wild',
 'creature',
 'as',
 'their',
 'king',
 'Max',
 'tame',
 'the',
 'beast',
 'and',
 'eventually',
 'return',
 'home',
 'to',
 'find',
 'his',
 'supper',
 'wait',
 'for',
 'he',
 'this',
 'iconic',
 'book',
 'explore',
 'theme',
 'of',
 'imagination',
 'adventure',
 'and',
 'the',
 'complex',
 'emotion',
 'of',
 'childhood',
 'all',
 'capture',
 'through',
 'Sendaks',
 'whimsical',
 'illustration',
 'and',
 'story']

In [10]:
norm = [token.lemma_ for token in doc if not token.is_stop]
norm

['Wild',
 'Things',
 '\xa0',
 'follow',
 'Max',
 'young',
 'boy',
 'send',
 'room',
 'misbehave',
 'imago',
 'sail',
 'island',
 'fill',
 'wild',
 'creature',
 'king',
 'Max',
 'tame',
 'beast',
 'eventually',
 'return',
 'home',
 'find',
 'supper',
 'wait',
 'iconic',
 'book',
 'explore',
 'theme',
 'imagination',
 'adventure',
 'complex',
 'emotion',
 'childhood',
 'capture',
 'Sendaks',
 'whimsical',
 'illustration',
 'story']

In [11]:
list(nlp.Defaults.stop_words)[:10]

['ours',
 'someone',
 'twenty',
 'until',
 '‘s',
 'itself',
 'call',
 'nor',
 'indeed',
 'never']

In [12]:
' '.join(norm)

'Wild Things \xa0 follow Max young boy send room misbehave imago sail island fill wild creature king Max tame beast eventually return home find supper wait iconic book explore theme imagination adventure complex emotion childhood capture Sendaks whimsical illustration story'

## token_lemma_nonstop()

In [13]:
def token_lemma_nonstop(text):
    doc = nlp(text)
    output = [token.lemma_ for token in doc if not token.is_stop]
    output = ' '.join(output)
    return output

lower_replace(df.cleaned_desc).apply(token_lemma_nonstop)

0                                    wild thing   follow max young boy send room misbehave imago sail island fill wild creature king max tame beast eventually return home find supper wait iconic book explore theme imagination adventure complex emotion childhood capture sendak whimsical illustration story
1                  hungry caterpillar   tell story caterpillar eat variety food eventually butterfly eric carles use colorful collage illustration rhythmic text book beloved classic young reader simple engaging story introduce child day week counting concept metamorphosis staple early childhood education
2                                                   give tree   touching bittersweet story tree give boy course life boy grow take tree tree continue little left silverstein minimalist text illustration convey deep theme unconditional love selflessness passage time spark discussion relationship sacrifice
3                green egg ham samiam try convince reluctant character try dish green egg ham despite resistance repetition rhyme dr seusss classic story open new experience encourage child adventurous try thing outside comfort zone playful illustration humorous dialogue fun educational read young reader
4                                   goodnight moon   gentle rhythmic bedtime story little bunny say goodnight room moon quiet old lady whispering hush repetitive structure comfort tone ideal young child simple illustration clement hurd complement soothe nature story make beloved classic sleeptime reading
                                                                                                                                                         ...
95                            stone soup   classic folktale retold jon j muth soldier arrive village claim soup stone villager initially hesitant eventually contribute ingredient pot create delicious meal story heartwarming lesson share community cooperation enhance muth beautiful watercolor illustration
96                light attic   collection quirky poem illustration shel silverstein explore wide range topic wit humor imagination poem funny thoughtful absurd carry sense wonder creativity silverstein distinctive voice whimsical illustration book timeless collection continue entertain child adult alike
97                   harry potter prisoner azkaban   book   harry potter   series harry return hogwart year uncover secret past arrival mysterious sirius black harry navigate dark truth face fear thrilling installment explore theme loyalty friendship identity mark turning point magical world harry potter
98                       harry potter chamber secret   second book   harry potter   series harry return hogwart second year uncover hidden chamber school mysterious event unfold harry friend ron hermione uncover dark secret school past theme courage friendship stand s right explore grip magical adventure
99    billy goat gruff   retelling classic norwegian fairy tale goat outwit greedy troll cross bridge reach green pasture goat come clever strategy trick troll teach child lesson teamwork bravery cleverness galdone illustration simple rhythmic text bring tale life way accessible entertaining young reader
Name: cleaned_desc, Length: 100, dtype: object

# 2. POS Tagging

In [14]:
phrase2 = lower_replace(df.cleaned_desc).apply(token_lemma_nonstop) [0]
phrase2

'wild thing \xa0 follow max young boy send room misbehave imago sail island fill wild creature king max tame beast eventually return home find supper wait iconic book explore theme imagination adventure complex emotion childhood capture sendak whimsical illustration story'

In [15]:
doc2 = nlp(phrase2)
doc2

wild thing   follow max young boy send room misbehave imago sail island fill wild creature king max tame beast eventually return home find supper wait iconic book explore theme imagination adventure complex emotion childhood capture sendak whimsical illustration story

In [16]:
pos = [(token.text, token.pos_) for token in doc2]
pos

[('wild', 'ADJ'),
 ('thing', 'NOUN'),
 ('\xa0 ', 'SPACE'),
 ('follow', 'VERB'),
 ('max', 'NOUN'),
 ('young', 'ADJ'),
 ('boy', 'NOUN'),
 ('send', 'VERB'),
 ('room', 'NOUN'),
 ('misbehave', 'NOUN'),
 ('imago', 'PROPN'),
 ('sail', 'PROPN'),
 ('island', 'PROPN'),
 ('fill', 'NOUN'),
 ('wild', 'ADJ'),
 ('creature', 'NOUN'),
 ('king', 'PROPN'),
 ('max', 'PROPN'),
 ('tame', 'PROPN'),
 ('beast', 'NOUN'),
 ('eventually', 'ADV'),
 ('return', 'VERB'),
 ('home', 'NOUN'),
 ('find', 'NOUN'),
 ('supper', 'NOUN'),
 ('wait', 'VERB'),
 ('iconic', 'ADJ'),
 ('book', 'NOUN'),
 ('explore', 'VERB'),
 ('theme', 'NOUN'),
 ('imagination', 'NOUN'),
 ('adventure', 'NOUN'),
 ('complex', 'ADJ'),
 ('emotion', 'NOUN'),
 ('childhood', 'NOUN'),
 ('capture', 'VERB'),
 ('sendak', 'PROPN'),
 ('whimsical', 'ADJ'),
 ('illustration', 'NOUN'),
 ('story', 'NOUN')]

In [17]:
nouns = [(token.text) for token in doc2 if token.pos_ in ['NOUN', "PROPN"]]
nouns

['thing',
 'max',
 'boy',
 'room',
 'misbehave',
 'imago',
 'sail',
 'island',
 'fill',
 'creature',
 'king',
 'max',
 'tame',
 'beast',
 'home',
 'find',
 'supper',
 'book',
 'theme',
 'imagination',
 'adventure',
 'emotion',
 'childhood',
 'sendak',
 'illustration',
 'story']

In [18]:
' '.join(nouns)

'thing max boy room misbehave imago sail island fill creature king max tame beast home find supper book theme imagination adventure emotion childhood sendak illustration story'

## filter_pos()

In [19]:
def filter_pos(text, pos_list = ['NOUN', 'PROPN']):
    doc = nlp(text)
    output = [(token.text) for token in doc if token.pos_ in pos_list]
    output = ' '.join(output)
    return output

lower_replace(df.Description).apply(token_lemma_nonstop).apply(filter_pos)

0                         thing max boy room misbehave imago sail island fill creature king max tame beast home find supper book theme imagination adventure emotion childhood sendak illustration story
1                       caterpillar story caterpillar eat variety food eric carles collage illustration text book reader story introduce child day week concept metamorphosis staple childhood education
2                                               tree story tree boy course life boy tree tree silverstein text illustration theme love selflessness passage time spark discussion relationship sacrifice
3                                        egg ham samiam convince character dish egg ham resistance repetition rhyme dr seusss story experience child thing comfort zone illustration dialogue fun reader
4                      moon bedtime story little bunny goodnight room moon lady whispering structure comfort tone ideal child illustration clement hurd complement soothe nature story sleeptime reading
                                                                                                     ...
95         stone soup folktale retold jon j muth soldier arrive village claim soup stone villager ingredient pot meal story heartwarming lesson share community cooperation muth watercolor illustration
96                                    collection quirky poem illustration shel silverstein range topic wit humor imagination poem sense wonder creativity voice illustration book collection child adult
97    harry potter prisoner book harry potter series harry return hogwart year arrival sirius black harry truth fear installment explore theme loyalty friendship identity mark point world harry potter
98     harry potter chamber secret book harry potter series harry return hogwart year hidden chamber school event harry friend ron hermione school theme courage friendship stand explore grip adventure
99                                      billy goat gruff fairy tale goat outwit troll cross bridge pasture goat strategy trick troll child lesson teamwork bravery galdone illustration text life reader
Name: Description, Length: 100, dtype: object

# 3. Creating a Custom NLP Pipeline

In [20]:
def nlp_pipeline(series):
    output = lower_replace(series)
    output = output.apply(token_lemma_nonstop)
    output = output.apply(filter_pos)
    return output

cleaned_text = nlp_pipeline(df.Description)

In [21]:
pd.to_pickle(cleaned_text, 'cleaned_text.pkl')

# CountVectorizer

In [22]:
series = pd.read_pickle('cleaned_text.pkl')
series

0                         thing max boy room misbehave imago sail island fill creature king max tame beast home find supper book theme imagination adventure emotion childhood sendak illustration story
1                       caterpillar story caterpillar eat variety food eric carles collage illustration text book reader story introduce child day week concept metamorphosis staple childhood education
2                                               tree story tree boy course life boy tree tree silverstein text illustration theme love selflessness passage time spark discussion relationship sacrifice
3                                        egg ham samiam convince character dish egg ham resistance repetition rhyme dr seusss story experience child thing comfort zone illustration dialogue fun reader
4                      moon bedtime story little bunny goodnight room moon lady whispering structure comfort tone ideal child illustration clement hurd complement soothe nature story sleeptime reading
                                                                                                     ...
95         stone soup folktale retold jon j muth soldier arrive village claim soup stone villager ingredient pot meal story heartwarming lesson share community cooperation muth watercolor illustration
96                                    collection quirky poem illustration shel silverstein range topic wit humor imagination poem sense wonder creativity voice illustration book collection child adult
97    harry potter prisoner book harry potter series harry return hogwart year arrival sirius black harry truth fear installment explore theme loyalty friendship identity mark point world harry potter
98     harry potter chamber secret book harry potter series harry return hogwart year hidden chamber school event harry friend ron hermione school theme courage friendship stand explore grip adventure
99                                      billy goat gruff fairy tale goat outwit troll cross bridge pasture goat strategy trick troll child lesson teamwork bravery galdone illustration text life reader
Name: Description, Length: 100, dtype: object

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
dtm = cv.fit_transform(series)
dtm_df = pd.DataFrame(dtm.toarray(), columns = cv.get_feature_names_out())
dtm_df

,aa,aaron,ability,absurd,absurdity,acceptance,accompany,accuracy,acre,action,...,world,worldbuilde,wrap,wrinkle,write,writing,year,young,zany,zone
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
99,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
cv2 = CountVectorizer(stop_words='english', ngram_range=(1, 2), min_df=2, max_df=.8)
cv2

CountVectorizer(max_df=0.8, min_df=2, ngram_range=(1, 2), stop_words='english')

In [25]:
dtm2 = cv2.fit_transform(series)
dtm_df2 = pd.DataFrame(dtm2.toarray(), columns=cv2.get_feature_names_out())
dtm_df2

,ability,absurdity,acceptance,action,adult,adventure,adventure friend,adventure lesson,age,american,...,witch wardrobe,wizard,wonder,wood,wood book,word,world,world book,world story,year
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
98,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# 5. EDA with CountVectorizer

In [26]:
term_freq = dtm_df2.sum()
term_freq

ability         2
absurdity       2
acceptance      4
action          4
adult           9
               ..
word            4
world          16
world book      2
world story     2
year            3
Length: 421, dtype: int64

In [31]:
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt

top_n = 30  # Show only the top 30 terms for clarity
top_terms = term_freq.sort_values(ascending=False).head(top_n)

fig = px.bar(x=top_terms.values, y=top_terms.index, labels={'x': 'Frequency', 'y': 'Term'}, title="Top 30 Term Frequencies")
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

# 6. TF-IDF Vectorizer

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer()
tfidf = tv.fit_transform(series)
tfidf_df = pd.DataFrame(tfidf.toarray(), columns=tv.get_feature_names_out())
tfidf_df

,aa,aaron,ability,absurd,absurdity,acceptance,accompany,accuracy,acre,action,...,world,worldbuilde,wrap,wrinkle,write,writing,year,young,zany,zone
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.23107
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000
96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000
97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.097984,0.0,0.0,0.0,0.0,0.0,0.142534,0.0,0.0,0.00000
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.154542,0.0,0.0,0.00000
99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.00000