# Text Preprocessing

### 0. Create Data Sets

In [1]:
import pandas as pd

data = [
    "When life gives you lemons, make lemonade! 🙂",
    "She bought 2 lemons for $1 at Maven Market.",
    "A dozen lemons will make a gallon of lemonade. [AllRecipes]",
    "lemon, lemon, lemons, lemon, lemon, lemons",
    "He's running to the market to get a lemon — there's a great sale today.",
    "Does Maven Market carry Eureka lemons or Meyer lemons?",
    "An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",
    "iced tea is my favorite"    
]

pd. set_option('display.max_colwidth', None)

data_df = pd.DataFrame(data, columns=["sentence"])
data_df

                                                                  sentence
0                             When life gives you lemons, make lemonade! 🙂
1                              She bought 2 lemons for $1 at Maven Market.
2              A dozen lemons will make a gallon of lemonade. [AllRecipes]
3                               lemon, lemon, lemons, lemon, lemon, lemons
4  He's running to the market to get a lemon — there's a great sale today.
5                   Does Maven Market carry Eureka lemons or Meyer lemons?
6            An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]
7                                                  iced tea is my favorite

In [2]:
test = [
    "We're going to start this course with traditional NLP applications.",
    "Then we'll move on to modern NLP theory.",
    "Finally, we'll wrap things up with modern NLP applications."
    
]

test_series = pd.Series(test)
test_series

0    We're going to start this course with traditional NLP applications.
1                               Then we'll move on to modern NLP theory.
2            Finally, we'll wrap things up with modern NLP applications.
dtype: object

## 1. Text Preprocessing with Pandas

In [3]:
df = data_df.copy()
df

                                                                  sentence
0                             When life gives you lemons, make lemonade! 🙂
1                              She bought 2 lemons for $1 at Maven Market.
2              A dozen lemons will make a gallon of lemonade. [AllRecipes]
3                               lemon, lemon, lemons, lemon, lemon, lemons
4  He's running to the market to get a lemon — there's a great sale today.
5                   Does Maven Market carry Eureka lemons or Meyer lemons?
6            An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]
7                                                  iced tea is my favorite

In [21]:
df['sentence_clean'] = df['sentence'].str.lower()
df

,sentence,sentence_clean
0,"When life gives you lemons, make lemonade! 🙂","when life gives you lemons, make lemonade! 🙂"
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for $1 at maven market.
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade. [allrecipes]
3,"lemon, lemon, lemons, lemon, lemon, lemons","lemon, lemon, lemons, lemon, lemon, lemons"
4,He's running to the market to get a lemon — there's a great sale today.,he's running to the market to get a lemon — there's a great sale today.
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons?
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]","an arnold palmer is half lemonade, half iced tea. [wikipedia]"
7,iced tea is my favorite,iced tea is my favorite

In [22]:
df['sentence_clean'] = df['sentence_clean'].str.replace(r'\[.*?\]', '', regex=True)
df

,sentence,sentence_clean
0,"When life gives you lemons, make lemonade! 🙂","when life gives you lemons, make lemonade! 🙂"
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for $1 at maven market.
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade.
3,"lemon, lemon, lemons, lemon, lemon, lemons","lemon, lemon, lemons, lemon, lemon, lemons"
4,He's running to the market to get a lemon — there's a great sale today.,he's running to the market to get a lemon — there's a great sale today.
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons?
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]","an arnold palmer is half lemonade, half iced tea."
7,iced tea is my favorite,iced tea is my favorite

In [23]:
df['sentence_clean'] = df['sentence_clean'].str.replace(r'[^\w\s]', '', regex=True)
df

,sentence,sentence_clean
0,"When life gives you lemons, make lemonade! 🙂",when life gives you lemons make lemonade
1,She bought 2 lemons for $1 at Maven Market.,she bought 2 lemons for 1 at maven market
2,A dozen lemons will make a gallon of lemonade. [AllRecipes],a dozen lemons will make a gallon of lemonade
3,"lemon, lemon, lemons, lemon, lemon, lemons",lemon lemon lemons lemon lemon lemons
4,He's running to the market to get a lemon — there's a great sale today.,hes running to the market to get a lemon theres a great sale today
5,Does Maven Market carry Eureka lemons or Meyer lemons?,does maven market carry eureka lemons or meyer lemons
6,"An Arnold Palmer is half lemonade, half iced tea. [Wikipedia]",an arnold palmer is half lemonade half iced tea
7,iced tea is my favorite,iced tea is my favorite

### Create a lower_replace function

In [24]:
def lower_replace (series):
    output = series.str.lower()
    output = output.str.replace(r'\[.*?\]', '', regex=True)
    output = output.str.replace(r'\[^\w\s]', '', regex=True)
    return output

In [25]:
lower_replace(test_series)

0    we're going to start this course with traditional nlp applications.
1                               then we'll move on to modern nlp theory.
2            finally, we'll wrap things up with modern nlp applications.
dtype: object

In [26]:
lower_replace(df.sentence)

0                               when life gives you lemons, make lemonade! 🙂
1                                she bought 2 lemons for $1 at maven market.
2                            a dozen lemons will make a gallon of lemonade.
3                                 lemon, lemon, lemons, lemon, lemon, lemons
4    he's running to the market to get a lemon — there's a great sale today.
5                     does maven market carry eureka lemons or meyer lemons?
6                         an arnold palmer is half lemonade, half iced tea.
7                                                    iced tea is my favorite
Name: sentence, dtype: object